### PR TITLE
Edit Client Profile DEV-356

### PR DESCRIPTION
**Pull request by Davit-BetterAngels**
DEV-356

edit client profile. 

This should not be merged until add client is resolved. this branch is behind https://github.com/BetterAngelsLA/monorepo/pull/395

refactored to combined Add and Edit Profile

### CODE REVIEW

**Review by mikefeldberg — COMMENTED** [review]
Is this the best approach to implement an edit screen? Could we modify the existing AddClient components to be used for both adding and editing?

**Comment by mikefeldberg** [comment]
something like this https://github.com/BetterAngelsLA/monorepo/pull/451

**Comment by Davit-BetterAngels** [comment]
> Is this the best approach to implement an edit screen? Could we modify the existing AddClient components to be used for both adding and editing?

take a look. refactored everything

**Review by mikefeldberg — CHANGES_REQUESTED** [review]
It looks like this branch was checked out from `main` before we reset githistory, and then the "new" `main` was merged into this branch. This PR should be closed and reopened from a new branch with just the affected files. 

image

**Comment by mikefeldberg** [comment]
replaced by #454 454

**Pull request closed without merging**
