### PR TITLE
Collection of User Consent for Data Processing (DEV-642)

### PR DESCRIPTION
**Pull request by davelindqvist**
[DEV-642](https://betterangels.atlassian.net/browse/DEV-642?atlOrigin=eyJpIjoiZGRjODM1MjkzOGIxNDBiOTllOWUzY2QyZWM3MDJlNTEiLCJwIjoiaiJ9)

[DEV-642]: https://betterangels.atlassian.net/browse/DEV-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

consent-agreements

---

If you want to reset the user settings to show the consent modal again, go to https://api.dev.betterangels.la/graphql

Input this query and then hit the play button:
```
query GetCurrentUser {
  currentUser {
    id
    hasAcceptedTos
    hasAcceptedPrivacyPolicy
  }
}
```

image

In return, you will get your ID.

Input this ID when you want to reset `hasAcceptedTos` and `hasAcceptedPrivacyPolicy` to false like this:

Mutation query:
```
mutation UpdateCurrentUser($data: UpdateUserInput!) {
  updateCurrentUser(data: $data) {
    ... on UserType {
      id
      hasAcceptedTos
      hasAcceptedPrivacyPolicy
    }
  }
}
```

Variables:
```
{
  "data": {
    "id": #### ENTER ID HERE ####,
    "hasAcceptedTos": false,
    "hasAcceptedPrivacyPolicy": false
  }
}
```

image

### CODE REVIEW

**Comment by davelindqvist** [comment]
I merged from main, which is why there's all those commits. I don't think this is best practice, so I can definitely redo this.

**Comment by davelindqvist** [comment]
Merged from `DEV-679/client-profile-uploads` to fix type error issues

**Comment by shiozakiyuko** [comment]
Hi @davelindqvist 

Thanks for working on this story.

I think it looks great except one thing if it's possible.

Can you move the check icon to the vertically center of the box as it shows in the mockup?
Thanks!

image
image

**Review by shiozakiyuko — COMMENTED** [review]
I left you a comment!

**Comment by davelindqvist** [comment]
> I left you a comment!

Ah, I didn't realize how awkward this looks like when the checkbox is `sm` (small). 

How would you feel if it was a `md` (medium) size instead? It would look like this:

image

**Comment by shiozakiyuko** [comment]
Hi @davelindqvist It looks great! Thanks so much!

**Review by shiozakiyuko — APPROVED** [review]

**Comment by mikefeldberg** [comment]
The client document upload work from #522 was pulled into and committed as part of this PR

**Pull request merged**
