### PR TITLE
Shetler db schema update without file upload (DEV-514)

### PR DESCRIPTION
**Pull request by vecchp**
#### Related to PR #462

This pull request addresses most tasks in DEV-514, except for file upload functionality, which turned out to be more complex than expected. Although file upload works, it currently doesn't display upload progress. This PR includes everything except that.

#### Changes:

1. **ShelterDB Schema Update**:
    - Modified the schema to align with the Google Doc in DEV-514.
    - Removed the duplicate location model and now store addresses directly on the model. If you can find a way to use the location model without requiring two modal dialogs in the admin form, please advise. The current necessity to navigate through multiple dialog popups is inconvenient.

2. **Rich Text Field Editing**:
    - Added support for rich text field editing.

3. **GraphQL Schema**:
    - Removed the GraphQL schema and related tests. No application currently uses it.

#### How to Test:

1. Go to the shelter admin page.
2. Create a new shelter with all fields populated.
3. Edit the newly created shelter to ensure updates work correctly.

### CODE REVIEW

**Comment by davelindqvist** [comment]
While editing the items within `Immediate Needs` under `Advanced Info`, it's unable to be saved if I check off clothing, food, or showers.

**Comment by davelindqvist** [comment]
I don't have access to the [Shelter DB Fields](https://docs.google.com/spreadsheets/u/1/d/1nKFqSEW9lMDjcKjyFIA2qG9zhS3NzszvUxUiML5Q5ao/edit?gid=651447003&pli=1), but I noticed the only things required are `Name`, `Phone`, `Description`, `Populations`, and `Total Beds`. Should that be the case?

**Comment by davelindqvist** [comment]
I keep getting this error even after the migration:

image

**Comment by vecchp** [comment]
> I keep getting this error even after the migration while trying to edit:
> 
> image

You’ll have it run the reset_db command since I updated an already run migration.  In the backend app directory python manage.py reset_db.

**Comment by vecchp** [comment]
> I don't have access to the [Shelter DB Fields](https://docs.google.com/spreadsheets/u/1/d/1nKFqSEW9lMDjcKjyFIA2qG9zhS3NzszvUxUiML5Q5ao/edit?gid=651447003&pli=1), but I noticed the only things required are `Name`, `Phone`, `Description`, `Populations`, and `Total Beds`. Is that all that's required?
> 
> Additionally, it appears that you can have multiple copies of the same shelter and unsure if that's intentional:
> 
> image

It is intentional atm. I don’t think we have a good agreement upon heuristic for that yet.

**Comment by davelindqvist** [comment]
Got it! Maybe we can have something in the backend documentation that has this?


> ### Resetting DB
> If an error occurs where the database isn't reflecting after the migrations, run:
> ```
> yarn nx run betterangels-backend:reset_db
> ```

I also noticed these fields are missing -- also intentional?
```
other details > ratings,
other details > review,
advanced info > shelter style, 
restrictions > drugs,
restrictions > program fees
```

Otherwise, I got the immediate needs portion working. LGTM

**Comment by vecchp** [comment]
> Got it! Maybe we can have something in the backend documentation that has this?
> 
> > ### Resetting DB
> > If an error occurs where the database isn't reflecting after the migrations, run:
> > ```
> > yarn nx run betterangels-backend:reset_db
> > ```
> 
> I also noticed these fields are missing -- also intentional?
> 
> ```
> other details > ratings,
> other details > review,
> advanced info > shelter style, 
> restrictions > drugs,
> restrictions > program fees
> ```
> 
> Otherwise, I got the immediate needs portion working. LGTM

Ratings and reviews won’t be done right now. They are much larger features and likely wont be uploaded by the users which enter in shelter information. 

I think I may have missed drugs so that needs to go in. 

I think programs fees should be a text field. Let me know if I missed that. 

Your suggestion for updating the documentation makes sense. Can you make a PR with those changes?

Thanks for the thorough review!

**Comment by davelindqvist** [comment]
There are two fees:

image

The bed fees are included, but I don't currently see the`Program fees` `boolean`

I'll go ahead and start the documentation PR shortly

**Comment by davelindqvist** [comment]
Per the conversation with John this morning at standup (July 15, 2024), I will be approving this PR so the volunteers are able to enter the database information with some caveats:

There are still three fields missing that needs to be implemented:

```
advanced info > shelter style (list)
restrictions > drugs (boolean)
restrictions > program fees (boolean)
```

**Review by davelindqvist — APPROVED** [review]
Per the conversation with John this morning at standup (July 15, 2024), I will be approving this PR so the volunteers are able to enter the database information with some caveats:

These are the missing three fields, which still need to be implemented:

```
advanced info > shelter style (list)
restrictions > drugs (boolean)
restrictions > program fees (boolean)
```

**Pull request merged**
